In [1]:
!pip install pandas

Collecting pandas
  Using cached pandas-1.5.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.1 MB)
Requirement already satisfied: python-dateutil>=2.8.1 in ./venv/lib/python3.10/site-packages (from pandas) (2.8.2)
Collecting pytz>=2020.1
  Using cached pytz-2022.7.1-py2.py3-none-any.whl (499 kB)
Collecting numpy>=1.21.0
  Using cached numpy-1.24.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
Requirement already satisfied: six>=1.5 in ./venv/lib/python3.10/site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)
Installing collected packages: pytz, numpy, pandas
Successfully installed numpy-1.24.2 pandas-1.5.3 pytz-2022.7.1

In [2]:
import pandas as pd

In [5]:
occupant_feedback_thermal_data = pd.read_csv('Occupant feedback thermal IAQ.csv')

In [6]:
occupant_feedback_thermal_data.head()

,Timestamp,Please select your seated position,Temperature [Overall],Temperature [Head],Temperature [Body],Temperature [Hand],Temperature [Leg],Air Movement [Overall],Air Movement [Head],Air Movement [Body],...,How satisfied are you with the following: [Air quality],Physical effects [Headaches],Physical effects [Difficulty in concentration],Physical effects [Dry skin],Physical effects [Sleepiness],Physical effects [Itching eyelids],Physical effects [Dry eyes],Physical effects [Throat irritation],Physical effects [Runny nose],Physical effects [Sneezing/coughing]
0,2023/03/03 2:34:42 pm GMT+5:30,10,Just nice,Slightly warm,Just nice,Just nice,Just nice,Just nice,Just nice,Just nice,...,Somewhat satisfied,Not at all,Not at all,Not at all,Not at all,Not at all,Not at all,A little,Not at all,Not at all
1,2023/03/03 2:35:03 pm GMT+5:30,8,Slightly warm,Slightly warm,Slightly warm,Just nice,Just nice,Too weak,Too weak,Too weak,...,Somewhat Dissatisfied,Not at all,A little,Not at all,A little,Not at all,Not at all,Not at all,Not at all,Not at all
2,2023/03/03 2:35:28 pm GMT+5:30,9,Slightly cool,Just nice,Just nice,Slightly cool,Slightly cool,Just nice,A little weak,A little weak,...,Satisfied,Not at all,Not at all,Not at all,Not at all,Not at all,Not at all,Not at all,Not at all,Not at all
3,2023/03/03 2:35:30 pm GMT+5:30,21,Just nice,Slightly warm,Just nice,Slightly cool,Slightly warm,Too weak,Too weak,Too weak,...,Neutral,Not at all,Not at all,Not at all,Not at all,Not at all,Not at all,Not at all,Not at all,Not at all
4,2023/03/03 2:35:47 pm GMT+5:30,1,Just nice,Slightly warm,Just nice,Just nice,Slightly cool,None,None,None,...,Neutral,Not at all,Not at all,Moderate,Not at all,Not at all,Not at all,Not at all,A little,A little

In [7]:
air_quality_data = pd.read_csv('Air quality data.csv')

In [8]:
air_quality_data.head()

           Timestamp  Humidity  Temperature  CarbonDioxide  Dust
0  3/3/2023 14:36:28      38.7         30.5          836.0  0.02
1  3/3/2023 14:51:28      40.4         30.8         1035.0  0.01
2  3/3/2023 15:06:28      41.4         31.1         1194.0  0.01
3  3/3/2023 15:21:28      41.1         31.4         1261.0  0.02
4  3/3/2023 15:36:28      42.1         31.5         1389.0  0.02

In [3]:
air_quality_data = pd.read_csv('Air quality data.csv')

In [4]:
air_quality_data.head()

           Timestamp  Humidity  Temperature  CarbonDioxide  Dust
0  3/3/2023 14:36:28      38.7         30.5          836.0  0.02
1  3/3/2023 14:51:28      40.4         30.8         1035.0  0.01
2  3/3/2023 15:06:28      41.4         31.1         1194.0  0.01
3  3/3/2023 15:21:28      41.1         31.4         1261.0  0.02
4  3/3/2023 15:36:28      42.1         31.5         1389.0  0.02

In [3]:
air_quality_data = pd.read_csv('Air quality data.csv')

In [4]:
air_quality_data.head()

           Timestamp  Humidity  Temperature  CarbonDioxide  Dust
0  3/3/2023 14:36:28      38.7         30.5          836.0  0.02
1  3/3/2023 14:51:28      40.4         30.8         1035.0  0.01
2  3/3/2023 15:06:28      41.4         31.1         1194.0  0.01
3  3/3/2023 15:21:28      41.1         31.4         1261.0  0.02
4  3/3/2023 15:36:28      42.1         31.5         1389.0  0.02

In [9]:
for sheet_name, df in xlsx_file.items():
    print(f"Sheet name: {sheet_name}")
    print(df.head(20))

Sheet name: Unnamed: 0
0     EVM0036_ENW020001_13032023_092821: Logged Data...
1                                                   NaN
2                                             Timestamp
3                                   2023-03-03 14:36:28
4                                   2023-03-03 14:51:28
5                                   2023-03-03 15:06:28
6                                   2023-03-03 15:21:28
7                                   2023-03-03 15:36:28
8                                   2023-03-03 15:51:28
9                                   2023-03-03 16:06:28
10                                  2023-03-03 16:21:28
11                                  2023-03-03 16:36:28
12                                  2023-03-03 16:51:28
13                                  2023-03-03 17:06:28
14                                  2023-03-03 17:21:28
Name: Unnamed: 0, dtype: object
Sheet name: Unnamed: 1
0          NaN
1          NaN
2     Humidity
3         38.7
4         40.4
5         41.4
6         41.1
7         42.1
8         41.9
9         41.1
10        41.5
11        35.4
12        33.9
13        33.2
14        34.9
Name: Unnamed: 1, dtype: object
Sheet name: Unnamed: 2
0             NaN
1             NaN
2     Temperature
3            30.5
4            30.8
5            31.1
6            31.4
7            31.5
8            31.2
9            31.4
10           31.4
11             32
12           32.5
13           32.6
14           32.4
Name: Unnamed: 2, dtype: object
Sheet name: Unnamed: 3
0               NaN
1               NaN
2     CarbonDioxide
3               836
4              1035
5              1194
6              1261
7              1389
8              1368
9              1359
10             1368
11              655
12              508
13              452
14              668
Name: Unnamed: 3, dtype: object
Sheet name: Unnamed: 4
0       NaN
1       NaN
2      Dust
3      0.02
4     0.013
5     0.014
6     0.019
7     0.017
8     0.019
9     0.016
10    0.011
11    0.013
12    0.012
13    0.009
14    0.009
Name: Unnamed: 4, dtype: object